### ISSUE TITLE
Elastic 6.0 support

### ISSUE THREAD

**Issue by tapir** [sohlich/elogrus#11]
Is there any work going on for elastic 6.0

https://github.com/olivere/elastic

**Comment by sohlich** [comment]
Contributions are welcome. Will look at this.

**Comment by subroll** [comment]
@sohlich, i've test the code using latest https://github.com/olivere/elastic, by modifying the import path and it works just fine..
please consider to create new tag to support elastic 6.0 or you want me made a pull request just for modifying import path.? 😂

**Comment by shousper** [comment]
I believe this can be closed :) https://github.com/sohlich/elogrus/pull/13

**Comment by sohlich** [comment]
Yep, let me take a breath :). I'd like to create a tag/branch and add some info to readme.
