### ISSUE TITLE
go get error from gopkg.in 

### ISSUE THREAD

**Issue by nianglao** [sohlich/elogrus#14]
When I run `go get gopkg.in/sohlich/elogrus`, 
there is an error.
`package gopkg.in/sohlich/elogrus: unrecognized import path "gopkg.in/sohlich/elogrus" (parse https://gopkg.in/sohlich/elogrus?go-get=1: no go-import meta tags ())` .

Where is wrong?

**Comment by sohlich** [comment]
Sorry, my fault. I'll add the tag so you will need to use go get github.com/sohlich/elogrus for the latest version. I'll add a branch for v3.

**Comment by sohlich** [comment]
fixed doc..please use go get gopkg.in/sohlich/elogrus.v3

**Comment by nianglao** [comment]
Thanks!
