### ISSUE TITLE
New Trace log level in logrus

### ISSUE THREAD

**Issue by dgsb** [sohlich/elogrus#15]
Hello, I'm just opening this issue to let you know, the next release of logrus (v1.2.0) will add a new trace level named Trace below Debug.
Here is the PR for reference sirupsen/logrus#844
You may want to take into account this new level.

**Comment by sohlich** [comment]
Thanks for letting me know. I'll take a look.

**Comment by lzxbill7** [comment]
> Thanks for letting me know. I'll take a look.

Hi sohlich, 
Nice to meet you!
Notice that you are looking for the maintainer of  this project. I want to join that. 
Cuttently I am using golang/logrus/elasticsearch, and this project help me building my work. I like to contribute some time and work to this project : )

**Comment by liuzoxan** [comment]
Merged! :-)
