### ISSUE TITLE
logrus's SetReportCaller invalid in elogrus

### ISSUE THREAD

**Issue by godcong** [sohlich/elogrus#17]
set `log.SetReportCaller(true) ` can displayed log with caller
but elk has no caller infos

**Comment by godcong** [comment]
too long time no result

**Comment by J7mbo** [comment]
If this library isn't maintained any more, I'll create a new one and advocate for that one instead...

**Comment by sanderdekoning** [comment]
@J7mbo did you ever think more about this idea?
