### ISSUE TITLE
Elasticsearch 5.0

### ISSUE THREAD

**Issue by jaksi** [sohlich/elogrus#2]
The go library for Elasticsearch [is available for version 5](https://godoc.org/gopkg.in/olivere/elastic.v5), while elogrus still uses v3.

Are there any plans to support v5?

**Comment by sohlich** [comment]
I'll look at it. Thanks for update. 👍

**Comment by sohlich** [comment]
simple support added, check v2. 
The context support added via Cancel func on hook.
