### ISSUE TITLE
Elasticsearch 7.0 support

### ISSUE THREAD

**Issue by Mimoja** [sohlich/elogrus#22]
elastic v7 released. elogrus is not ready yet?

**Comment by liuzoxan** [comment]
> elastic v7 released. elogrus is not ready yet?

Hi Mimoja, 
Thank you for creating the issue.
v7 support is ready right now. If you have any issue please feel free to contact me  :)
I will close this issue, now.

**Comment by Mimoja** [comment]
Will try - thank you :)
