### ISSUE TITLE
Apply for the maintainer

### ISSUE THREAD

**Issue by liuzoxan** [sohlich/elogrus#25]
Hi Sohlich,
Nice meeting you. I leave you a message on the twitter, but I am not sure you will see the message, because you did not tweet much. So I create a issue here hoping you can contact me, I am using the elogrus, and I want to be maintainer for the project.

Liuzoxan

**Comment by sohlich** [comment]
Hi Liuzoxan,
nice to meet you! Sorry, I'm a bit short on time since I have a family :D. I'm glad that there is someone who would like to maintain this project. I've added you as a collaborator of this repository. 

Rado
