### ISSUE TITLE
Report Caller missing

### ISSUE THREAD

**Issue by sanderdekoning** [sohlich/elogrus#27]
When I configure logrus in the following manner:

```	
logrus.SetFormatter(&logrus.JSONFormatter{})
logrus.SetReportCaller(true)
logrus.SetOutput(os.Stdout)
```

And add the elogrus hook:

```
hook, err := elogrus.NewAsyncElasticHook(client, "localhost", logrus.TraceLevel, index)
logrus.AddHook(hook)
```

The report caller output is shown in Stdout, however it is not present in Elasticsearch/Kibana.

**How can these fields (file and func) be included?**

**Comment by sanderdekoning** [comment]
See PR https://github.com/sohlich/elogrus/pull/29

**Comment by sanderdekoning** [comment]
And for trace level PR https://github.com/sohlich/elogrus/pull/28

**Comment by ycg000344** [comment]
haha~same question.

**Comment by liuzoxan** [comment]
Hi guys, 
Sorry I am late,  I will merge your requests. That is helpful for everyone!

**Comment by liuzoxan** [comment]
Thank you!

> See PR #29
