### ISSUE TITLE
Hook not Fire()ed in a goroutine, causing application hangs

### ISSUE THREAD

**Issue by Xiol** [sohlich/elogrus#8]
Hi,

As per the comment in the [logrus hook](https://github.com/sirupsen/logrus/blob/master/hooks.go#L3-L7) code, it's expected that hooks will handle their own goroutines. It doesn't seem like you're firing your hook in a goroutine (and I can't see the elastic library doing so), so if ElasticSearch is running slowly for whatever reason, it will block until the requests are complete.

I'm not entirely sure if it's as simple as just setting the `client...Do()` call to run in a goroutine or not?

Thanks

**Comment by efairon** [comment]
client...Do() is not a goroutine.

We forked and adapt the code to run in go routine.
Be aware you can't handle the error returned by elasticsearch ...

In our case we don't care, we need the log to be fast. Using the goroutine is 1000 times faster than original code.

![](http://storage7.static.itmages.com/i/17/0920/h_1505888342_9544781_36c946f82e.png)

**Comment by sohlich** [comment]
The problem here is that you can leak the goroutines because this concept is fire and forget. And in extream case, you will get in troubles. Maybe this could be handled by pooling, so let's say you can have 20 parallel requests to elastic in one time.

**Comment by sohlich** [comment]
The asynchronous hook added you can create the async hook by NewAsyncElasticHook function.
